cc_library(
    name = 'jsoncpp',
    srcs = [
        'json_reader.cpp',
      	'json_value.cpp',
      	'json_writer.cpp',
    ],
    #deps = '#rt',
    #incs = ['include', 'compat'],
    #export_incs = 'include',
    #defs = 'HAVE_CONFIG_H'
)

