cc_library(
    name = 'ctemplate',
    srcs = [
        'src/base/arena.cc',
        'src/per_expand_data.cc',
        'src/template.cc',
        'src/template_annotator.cc',
        'src/template_cache.cc',
        'src/template_dictionary.cc',
        'src/template_modifiers.cc',
        'src/template_namelist.cc',
        'src/template_pathops.cc',
        'src/template_string.cc',
        'src/htmlparser/htmlparser.cc',
        'src/htmlparser/jsparser.cc',
        'src/htmlparser/statemachine.cc',
    ],
    incs = [
        'src'
    ],
    export_incs = [
        'src'
    ],
    deps = [
        '//common/net:net'
    ],
    warning = 'no'
)
