cc_library(
    name = 'snappy-1.0.5',
    srcs = [
        'snappy.cc',
        'snappy-c.cc',
        'snappy-sinksource.cc',
        'snappy-stubs-internal.cc',
    ],
    extra_cppflags = '-Wno-sign-compare'
)

